title = "ASD talks"
baseURL = "http//asdtalks.com"
languageCode = "en-us"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "ASD (autism spectrum disorder) talks"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "red"
  author = "matthew swan"
  favicon = ""
  site_logo = ""
  description = "testing testing testing"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  body_classes = "avenir bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/matthew85869876"